{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:2: AssertionError"}, "start": 1703105237279, "stop": 1703105237279, "uuid": "88d861c3-dc44-4547-bf8d-62c37cd219bd", "historyId": "1598af888f7d3392b76686e9dcbff5ee", "testCaseId": "1598af888f7d3392b76686e9dcbff5ee", "fullName": "tests.simple.test_fail#test_fail", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "Vitalii"}, {"name": "thread", "value": "18552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}