{"name": "test_fail5", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail5():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:12: AssertionError"}, "start": 1703884252669, "stop": 1703884252669, "uuid": "5520abe4-3756-4914-8d78-615ec5731984", "historyId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "testCaseId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "fullName": "tests.simple.test_fail#test_fail5", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "Vitalii"}, {"name": "thread", "value": "25856-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}