{"name": "test_fail6", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail6():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:15: AssertionError"}, "start": 1703105237354, "stop": 1703105237354, "uuid": "714fffb3-bf5b-4833-b28a-29e96803013a", "historyId": "9ebd70578965c6a6474c5346ee5a0af2", "testCaseId": "9ebd70578965c6a6474c5346ee5a0af2", "fullName": "tests.simple.test_fail#test_fail6", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "Vitalii"}, {"name": "thread", "value": "18552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}