{"name": "test_fail4", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail4():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:9: AssertionError"}, "start": 1703105237350, "stop": 1703105237350, "uuid": "2835aa28-558c-45cb-b687-6d6cc6b223a0", "historyId": "f9f49e04500ac018e8389a41fc795dc7", "testCaseId": "f9f49e04500ac018e8389a41fc795dc7", "fullName": "tests.simple.test_fail#test_fail4", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "Vitalii"}, {"name": "thread", "value": "18552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}