{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:2: AssertionError"}, "start": 1703884252535, "stop": 1703884252536, "uuid": "221e0fe8-fc3d-43ef-ad8f-6dd7a9cd85d3", "historyId": "1598af888f7d3392b76686e9dcbff5ee", "testCaseId": "1598af888f7d3392b76686e9dcbff5ee", "fullName": "tests.simple.test_fail#test_fail", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "Vitalii"}, {"name": "thread", "value": "25856-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}